name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change if your main branch is named differently

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gui-ftp:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gui-ftp:latest

    - name: Add Username and Password
      run: docker run -d --name ftp-test -p 21:21 -p 30000-30009:30000-30009 -e FTP_USER_NAME=wla -e FTP_USER_PASS=wla123 -e FTP_USER_HOME=/home/test -v C:/pyftp:/home/test stilliard/pure-ftpd:hardened
